# Generated by Django 4.2 on 2023-07-07 11:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='oyunAciklama',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
