# Generated by Django 4.2 on 2023-07-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0008_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
